// Periods are relative to Earth's year. Display distances and sizes are illustrative.
export const EARTH_YEAR_SECONDS = 60;
export const EARTH_YEAR_DAYS = 365.256;
export const BODIES = [
  {id:'sun',parentId:null,name:'太陽',english:'SUN',category:'恒星',categoryEn:'Star',radius:3.6,orbitRadius:0,orbitalPeriodYears:0,spinPeriodSeconds:36,tilt:7.25,phase:0,texture:'sun',color:'#edb36c',description:'太陽系の中心で輝く恒星。高温のガスでできていて、その光と熱が地球の生命を支えています。太陽自身もゆっくりと自転しています。',descriptionEn:'The star at the center of our solar system. This immense sphere of hot gas provides the light and heat that sustain life on Earth, while slowly rotating on its own axis.'},
  {id:'mercury',parentId:'sun',name:'水星',english:'MERCURY',category:'地球型惑星',categoryEn:'Terrestrial planet',radius:.47,orbitRadius:8,orbitalPeriodYears:.24085,spinPeriodSeconds:30,tilt:.03,phase:.45,texture:'rock',color:'#ada398',description:'太陽に最も近い、いちばん小さな惑星。表面にはたくさんのクレーターがあり、約88日で太陽を一周します。',descriptionEn:'The smallest planet and the closest to the Sun. Its cratered surface completes a trip around the Sun in about 88 Earth days.'},
  {id:'venus',parentId:'sun',name:'金星',english:'VENUS',category:'地球型惑星',categoryEn:'Terrestrial planet',radius:.9,orbitRadius:12,orbitalPeriodYears:.61520,spinPeriodSeconds:32,tilt:177.4,phase:2.0,texture:'venus',color:'#dbc093',description:'厚い雲に包まれた、地球とほぼ同じ大きさの惑星。強い温室効果で表面は高温になり、多くの惑星とは逆向きに自転します。',descriptionEn:'A world nearly the size of Earth, hidden beneath thick clouds. An intense greenhouse effect heats its surface, and it rotates opposite to most planets.'},
  {id:'earth',parentId:'sun',name:'地球',english:'EARTH',category:'地球型惑星',categoryEn:'Terrestrial planet',radius:1,orbitRadius:17,orbitalPeriodYears:1,spinPeriodSeconds:12,tilt:23.44,phase:3.6,texture:'earth',color:'#76b4d4',description:'私たちの暮らす、水と生命の惑星。青い海、陸地、白い雲が表面を彩ります。約365日で太陽を一周し、そばには月が寄り添います。',descriptionEn:'Our home: a world of water and life, patterned by blue oceans, continents, and white clouds. Earth orbits the Sun in about 365 days, accompanied by the Moon.'},
  {id:'mars',parentId:'sun',name:'火星',english:'MARS',category:'地球型惑星',categoryEn:'Terrestrial planet',radius:.65,orbitRadius:23,orbitalPeriodYears:1.88085,spinPeriodSeconds:13,tilt:25.19,phase:5.25,texture:'mars',color:'#cc896b',description:'酸化鉄を含む地表が赤く見える惑星。巨大な火山や深い峡谷があり、極地には氷が広がっています。季節の変化もある世界です。',descriptionEn:'Iron minerals give this planet its rusty red color. Mars has enormous volcanoes, deep canyons, polar ice, and changing seasons.'},
  {id:'jupiter',parentId:'sun',name:'木星',english:'JUPITER',category:'巨大ガス惑星',categoryEn:'Gas giant',radius:2.65,orbitRadius:32,orbitalPeriodYears:11.8626,spinPeriodSeconds:7,tilt:3.13,phase:5.86,texture:'jupiter',color:'#c9a27e',description:'太陽系で最大の惑星。大気には幾重もの雲の縞が走り、「大赤斑」と呼ばれる巨大な嵐が渦巻きます。大きな体でも自転は速い惑星です。',descriptionEn:'The largest planet in the solar system. Bands of cloud wrap its atmosphere, while the Great Red Spot marks a giant storm. Despite its size, Jupiter spins quickly.'},
  {id:'saturn',parentId:'sun',name:'土星',english:'SATURN',category:'巨大ガス惑星',categoryEn:'Gas giant',radius:2.25,orbitRadius:44,orbitalPeriodYears:29.4475,spinPeriodSeconds:8,tilt:26.73,phase:2.55,texture:'saturn',color:'#d5c298',ring:true,description:'氷や岩の粒からなる、美しい環をまとった惑星。主に水素とヘリウムでできた巨大なガスの世界で、約29年かけて太陽を一周します。',descriptionEn:'A gas giant encircled by spectacular rings made of ice and rock. Saturn consists mainly of hydrogen and helium and takes about 29 Earth years to orbit the Sun.'},
  {id:'uranus',parentId:'sun',name:'天王星',english:'URANUS',category:'巨大氷惑星',categoryEn:'Ice giant',radius:1.55,orbitRadius:56,orbitalPeriodYears:84.0168,spinPeriodSeconds:10,tilt:97.77,phase:.8,texture:'uranus',color:'#a5d8d7',description:'淡い青緑色をした惑星。自転軸が大きく傾き、横倒しに近い姿で太陽をめぐります。大気中のメタンが赤い光を吸収し、青みを生みます。',descriptionEn:'A pale blue-green planet with an extreme axial tilt, orbiting almost on its side. Methane in its atmosphere absorbs red light and gives Uranus its color.'},
  {id:'neptune',parentId:'sun',name:'海王星',english:'NEPTUNE',category:'巨大氷惑星',categoryEn:'Ice giant',radius:1.5,orbitRadius:68,orbitalPeriodYears:164.7913,spinPeriodSeconds:9,tilt:28.32,phase:3.7,texture:'neptune',color:'#7295c9',description:'8つの惑星の中で、太陽から最も遠い惑星。冷たい大気には強い風が吹き、太陽を一周するには地球の約165年もの時間がかかります。',descriptionEn:'The most distant of the eight planets. Fierce winds sweep through its cold atmosphere, and one journey around the Sun takes about 165 Earth years.'},
  {id:'moon',parentId:'earth',name:'月',english:'MOON',category:'地球の衛星',categoryEn:"Earth's moon",radius:.3,orbitRadius:2.15,orbitalPeriodYears:27.3/EARTH_YEAR_DAYS,spinPeriodSeconds:null,tilt:0,phase:.3,texture:'moon',color:'#b2b4bb',description:'地球を約27.3日でめぐる衛星。自転と公転が同期し、いつもほぼ同じ面を地球に向けています。表面には無数のクレーターがあります。',descriptionEn:'Earth’s natural satellite completes an orbit in about 27.3 days. Its rotation is synchronized with its orbit, so nearly the same face always points toward Earth.'},
];
export const BODY_BY_ID = new Map(BODIES.map(body => [body.id,body]));
